version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=GamingPlatforms
      - MYSQL_ROOT_PASSWORD=Baklava21

volumes:
  db:
    driver: local